name: cd

on:
  push:
    tags:
      - "*"
    branches: [ wall-171-ios ]


jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # - name: Validate tag is valid
    #   run: |
    #     echo "${{ github.ref_name }}" | grep -P '^[0-9]+\.[0-9]+\.[0-9]+$'

  main:
    runs-on: macos-14
    needs: validation
    steps:
    - uses: actions/checkout@v4

    - name: Install tools
      uses: jdx/mise-action@v2
    - name: Set up XCode
      uses: mxcl/xcodebuild@v2
      with:
        xcode: 15.2
        action: none
    - name: Generate XCode project
      run: tuist generate -n

    - name: Import code sign
      uses: Apple-Actions/import-codesign-certs@master
      with:
        p12-file-base64: ${{ secrets.APPSTORE_IOS_DISTRIBUTION_CERTIFICATES }}
        p12-password: ${{ secrets.APPSTORE_IOS_DISTRIBUTION_CERTIFICATES_PASSWORD }}

    - name: Download provisioning
      uses: Apple-Actions/download-provisioning-profiles@master
      with:
        bundle-id: com.spruceid.wallet
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

    - name: Build and sign archive
      run: |
        # xcodebuild -parallelizeTargets -archivePath "./archive" CURRENT_PROJECT_VERSION="${{ github.ref_name }}" archive -scheme release
        xcodebuild -parallelizeTargets -archivePath "./archive" CURRENT_PROJECT_VERSION="0.0.0" archive -scheme release CODE_SIGNING_ALLOWED="NO"
        xcodebuild -exportArchive -exportOptionsPlist "Support/ExportOptions.plist" -archivePath "./archive.xcarchive" -exportPath "release.ipa"

    - name: Upload to TestFlight
      uses: Apple-Actions/upload-testflight-build@master
      with:
        app-path: release.ipa
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
